apiVersion: v1
kind: Pod
metadata:
  labels:
    backup: snapshot
  name: backup-snapshot
spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: "${AWS_ACCESS_KEY_ID}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "${AWS_SECRET_ACCESS_KEY}"
        - name: AWS_DEFAULT_REGION
          value: "${AWS_DEFAULT_REGION}"
        - name: DEFAULT_RETENTION_DAYS
          value: "${DEFAULT_RETENTION_DAYS}"
        image: getupcloud/aws-volume-snapshot:latest
        imagePullPolicy: IfNotPresent
        name: backup
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 300
